owner: Sabari-Vijayan
repo: status.app.ktu.in

sites:
  - name: KTU Main Website
    url: https://ktu.edu.in/
    __dangerous__disable_verify_peer: true 
    __dangerous__body_down: "Internal Server Error"

status-website:
  # Crucial: Leading and trailing slashes are required for sub-folders
  baseUrl: /status.app.ktu.in/
